# which go to the model you want to use
cfg_root: "/home/eureka/code/OpenPCDet/tools/cfgs/kitti_models/pv_rcnn.yaml"

# which go to the .pth
model_path: "/home/eureka/code/OpenPCDet/tools/pv_rcnn_8369.pth"

# pointcloud_topic in the bag if you are not sure
# rosbag info xxx.bag check the topic name
pointcloud_topic: "/global_manager/merged_cloud"  # "/global_manager/increment_cloud"  #   # "/velodyne_points" # default is from kitti2bag: /velodyne_points

# only the predict probablity over this threshold will be draw a box
threshold: 0.3

viz_rate: 1.0

# pointcloud recognition frequency
process_every_n_frames: 5
